/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cleanservices;

import javax.swing.JOptionPane;

/**
 *
 * @author olive
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
      
        
    }
    public void Admin(){

    }
    public void Cajero(){
        menuAdmin.setVisible(false);
        
    }
    // TODO add your handling code here:

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        titulo = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuAdmin = new javax.swing.JMenu();
        btnUsuario = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        btnReportes = new javax.swing.JMenuItem();
        Salida = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escritorio.setBackground(new java.awt.Color(204, 255, 204));

        titulo.setFont(new java.awt.Font("Agency FB", 1, 90)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Clean Services");
        escritorio.add(titulo);
        titulo.setBounds(30, 30, 480, 90);

        jLabel_fondo.setBackground(new java.awt.Color(255, 0, 0));
        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menuBack.jpg"))); // NOI18N
        jLabel_fondo.setMaximumSize(new java.awt.Dimension(1620, 780));
        jLabel_fondo.setMinimumSize(new java.awt.Dimension(1520, 680));
        escritorio.add(jLabel_fondo);
        jLabel_fondo.setBounds(0, 0, 1250, 620);

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 650));

        menuBar.setBackground(new java.awt.Color(153, 153, 153));

        menuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mantenimiento_32.png"))); // NOI18N
        menuAdmin.setText("Mantenimiento");
        menuAdmin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report_32.png"))); // NOI18N
        btnUsuario.setText("Usuarios");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        menuAdmin.add(btnUsuario);

        menuBar.add(menuAdmin);

        mnuReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reportes_32.png"))); // NOI18N
        mnuReport.setText("Reportes");
        mnuReport.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report_32.png"))); // NOI18N
        btnReportes.setText("Ver Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        mnuReport.add(btnReportes);

        menuBar.add(mnuReport);

        Salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salir_32.png"))); // NOI18N
        Salida.setText("Cerrar Sesion");
        Salida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Salida.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                SalidaMenuSelected(evt);
            }
        });
        menuBar.add(Salida);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalidaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_SalidaMenuSelected
       int resp=JOptionPane.showConfirmDialog(this,"¿Desea Cerrar Sesion?","Salir",JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(resp==0){
            this.dispose();
            LoginForm a = new LoginForm();
            a.setVisible(true);
        }
    }//GEN-LAST:event_SalidaMenuSelected

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        formReportes abrir = new formReportes();
        this.escritorio.add(abrir);
        abrir.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
        formUsuario abrir = new formUsuario();
        this.escritorio.add(abrir);
        abrir.setVisible(true);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Salida;
    private javax.swing.JMenuItem btnReportes;
    private javax.swing.JMenuItem btnUsuario;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
